---
deployment:
  tasks:
    - export SOURCEPATH=/home/joaomar9/repositories/home
    - export DEPLOYPATH=/home/joaomar9/public_html
    - /bin/cp -rf $SOURCEPATH/index.html $DEPLOYPATH/
    - /bin/cp -rf $SOURCEPATH/projetos.html $DEPLOYPATH/
    - /bin/cp -rf $SOURCEPATH/painel $DEPLOYPATH/
